-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjBcthQxmiYodYNcHks9upPGXKxtwomZHx0U0n7hUiRygCgYIKoZIzj0DAQehRANCAARJ0tchRJezmrEqWsqhzesHTSdHGTODAKB/ldliYWohKCHs9ii83YPp3PjymxInevFZfKZAOHmTLcO09XE5A3je
-----END PRIVATE KEY-----